name: textfixer_android
description: AI-powered text correction and enhancement for Android. Fix grammar, spelling, and style instantly with advanced AI technology.

publish_to: 'none'

version: 2.5.0+6

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  device_info_plus: ^10.1.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Noto Serif Display
      fonts:
        - asset: fonts/NotoSerifDisplay-Variable.ttf
